### ISSUE TITLE
Unknown flags for authorities command

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/acert#16]
```
Davids-MBP-4:acert dtillery$ acert authorities export MY_FINGERPRINT -f pem -t authority
Error: unknown shorthand flag: 'f' in -f
```

Works ok with leaves...

**Comment by chrisbsmith** [comment]
@tilleryd what version of acert are you running?  `acert version`.  I just tested and the export worked for me.
```console
➜  acert git:(master) acert version
acert 0.2.1-dev (29aa52f)
```
```console
➜  acert git:(master) acert authorities list
d5352358a9ec	Development (Intermediate)	2030-01-21 16:13:55 +0000 UTC
➜  acert git:(master) acert authorities export -f pem d5352358a9ec
-----BEGIN CERTIFICATE-----
goobly gop
-----END CERTIFICATE-----

➜  acert git:(master)
```

**Comment by tilleryd** [comment]
Davids-MBP-4:acert dtillery$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
Davids-MBP-4:acert dtillery$ make build
--> Vendoring dependencies...
--> Building binary...
Davids-MBP-4:acert dtillery$ acert version
acert 0.1.1 (5e5e4f4)

**Comment by tilleryd** [comment]
I don't understand, I'm missing something simple...

**Comment by tilleryd** [comment]
My problem stemmed from many months ago when I tested the initial version of `acert` with @joshua-rutherford . I had the binary in my path.

```
Davids-MBP-4:acert dtillery$ ./bin/acert version
acert 0.2.1-dev (29aa52f)
```
